### PR TITLE
Change API version (?) to 1.0.3

### PR DESCRIPTION
**Pull request by gontadu**
Small change to reflect what is on the web documentation

### CODE REVIEW

**Comment by brutus-gr** [comment]
Great, thanks!

**Comment by gontadu** [comment]
You're welcome! Do you have a Python 3 version in the works @jacobtylerdavis ? Otherwise, I'm in the process of writing one. Happy to transfer ownership later.

Here it is:
https://gitlab.com/gontadu/pyoneforge

**Comment by brutus-gr** [comment]
@gontadu Sorry for the delay getting back with you.

We don't have a python 3 version - thanks for sharing the one you made!

**Comment by gontadu** [comment]
@jacobtylerdavis No problem - let me know there if there are any issues.

**Pull request merged**
